package com.eaaa.glasscow.service;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import static com.eaaa.glasscow.service.DatabaseFields.FIELD_ID;
import static com.eaaa.glasscow.service.DatabaseFields.FIELD_JSON;
import static com.eaaa.glasscow.service.DatabaseFields.TABLE_COW;

public class CreateCows
{
	SQLiteDatabase db;
	public CreateCows(SQLiteDatabase db)
	{
		this.db = db;
	}
	
	public void createCow1()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407002146\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407002146\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407002146\","
                +    "\"EventDate\": \"2014-06-22T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407002146\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407002146\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407002146\","
                + "\"AnimalId\": \"04407002146\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 2,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-01-21T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 10,"
                + "\"CullingText\": \"Behold\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "2146");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow2()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407002145\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407002145\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407002145\","
                +    "\"EventDate\": \"2014-04-28T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407002145\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407002145\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407002145\","
                + "\"AnimalId\": \"04407002145\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-01-28T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "2145");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow3()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407001440\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407001440\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407001440\","
                +    "\"EventDate\": \"2014-05-05T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407001440\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407001440\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407001440\","
                + "\"AnimalId\": \"04407001440\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 2,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-01-21T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 10,"
                + "\"CullingText\": \"Behold\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1440");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow4()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407001443\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407001443\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407001443\","
                +    "\"EventDate\": \"2014-05-12T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407001443\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407001443\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407001443\","
                + "\"AnimalId\": \"04407001443\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-02-04T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1443");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow5()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407001430\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407001430\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407001430\","
                +    "\"EventDate\": \"2014-05-19T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407001430\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407001430\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407001430\","
                + "\"AnimalId\": \"04407001430\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 4,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-02-11T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 10,"
                + "\"CullingText\": \"Behold\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1430");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow6()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407001421\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407001421\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407001421\","
                +    "\"EventDate\": \"2014-05-26T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407001421\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407001421\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407001421\","
                + "\"AnimalId\": \"04407001421\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-02-18T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1421");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow7()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407001435\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407001435\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407001435\","
                +    "\"EventDate\": \"2014-06-01T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407001435\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407001435\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407001435\","
                + "\"AnimalId\": \"04407001435\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-02-25T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 10,"
                + "\"CullingText\": \"Behold\","
               + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1435");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow8()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407001444\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407001444\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407001444\","
                +    "\"EventDate\": \"2014-06-08T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407001444\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407001444\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407001444\","
                + "\"AnimalId\": \"04407001444\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-03-05T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1444");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow9()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407001257\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407001257\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
                + "{"
                +    "\"Id\": \"189290830\","
                +    "\"CowIndexCardMobileId\": \"04407001257\","
                +    "\"EventDate\": \"2014-06-15T00:00:00\","
                +    "\"Text\": \"Inseminering\","
                +    "\"Code\": 4"
                + "},"
                + "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407001257\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407001257\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407001257\","
                + "\"AnimalId\": \"04407001257\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": \"true\","
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2015-03-11T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1257");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
}
