package com.eaaa.glasscow.service;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import static com.eaaa.glasscow.service.DatabaseFields.FIELD_ID;
import static com.eaaa.glasscow.service.DatabaseFields.FIELD_JSON;
import static com.eaaa.glasscow.service.DatabaseFields.TABLE_COW;

public class CreateCows
{
	SQLiteDatabase db;
	public CreateCows(SQLiteDatabase db)
	{
		this.db = db;
	}
	
	public void createCow1()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407002146\","
                + "\"IllnessDate\": \"2014-04-07T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407002146\","
                + "\"IllnessDate\": \"2014-01-16T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407002146\","
				+ "\"EventDate\": \"2014-01-24T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407002146\","
                + "\"EventDate\": \"2013-11-29T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407002146\","
                + "\"AnimalId\": \"04407002146\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 27.4,"
                + "\"KgMilkLast12Months\": 9943,"
                + "\"KgECMLast12Months\": 10160,"
                + "\"LastCalvingDate\": \"2013-06-25T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"164\","
                + "\"ExpectedCalvingDate\": \"2014-11-21T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-09T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "2146");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow2()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"04407002145\","
                + "\"IllnessDate\": \"2014-04-08T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"04407002145\","
                + "\"IllnessDate\": \"2014-01-17T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"04407002145\","
				+ "\"EventDate\": \"2014-01-25T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"04407002145\","
                + "\"EventDate\": \"2013-11-30T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"04407002145\","
                + "\"AnimalId\": \"04407002145\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 28.4,"
                + "\"KgMilkLast12Months\": 9953,"
                + "\"KgECMLast12Months\": 10260,"
                + "\"LastCalvingDate\": \"2013-06-26T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"165\","
                + "\"ExpectedCalvingDate\": \"2014-11-22T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-10T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "2145");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow3()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"06524601440\","
                + "\"IllnessDate\": \"2014-04-09T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"06524601440\","
                + "\"IllnessDate\": \"2014-01-18T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"06524601440\","
				+ "\"EventDate\": \"2014-01-26T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"06524601440\","
                + "\"EventDate\": \"2013-12-01T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"06524601440\","
                + "\"AnimalId\": \"06524601440\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 27.5,"
                + "\"KgMilkLast12Months\": 9963,"
                + "\"KgECMLast12Months\": 10360,"
                + "\"LastCalvingDate\": \"2013-06-27T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"166\","
                + "\"ExpectedCalvingDate\": \"2014-11-23T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-11T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1440");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow4()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"06524601443\","
                + "\"IllnessDate\": \"2014-04-10T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"06524601443\","
                + "\"IllnessDate\": \"2014-01-19T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"06524601443\","
				+ "\"EventDate\": \"2014-01-27T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"06524601443\","
                + "\"EventDate\": \"2013-12-02T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"06524601443\","
                + "\"AnimalId\": \"06524601443\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 27.6,"
                + "\"KgMilkLast12Months\": 9973,"
                + "\"KgECMLast12Months\": 10460,"
                + "\"LastCalvingDate\": \"2013-06-28T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"167\","
                + "\"ExpectedCalvingDate\": \"2014-11-24T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-12T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1443");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow5()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"06524601430\","
                + "\"IllnessDate\": \"2014-04-11T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"06524601430\","
                + "\"IllnessDate\": \"2014-01-20T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"06524601430\","
				+ "\"EventDate\": \"2014-01-28T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"06524601430\","
                + "\"EventDate\": \"2013-12-03T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"06524601430\","
                + "\"AnimalId\": \"06524601430\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 27.7,"
                + "\"KgMilkLast12Months\": 9983,"
                + "\"KgECMLast12Months\": 10560,"
                + "\"LastCalvingDate\": \"2013-06-29T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"168\","
                + "\"ExpectedCalvingDate\": \"2014-11-25T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-13T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1430");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow6()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"06524601421\","
                + "\"IllnessDate\": \"2014-04-12T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"06524601421\","
                + "\"IllnessDate\": \"2014-01-21T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"06524601421\","
				+ "\"EventDate\": \"2014-01-29T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"06524601421\","
                + "\"EventDate\": \"2013-12-04T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"06524601421\","
                + "\"AnimalId\": \"06524601421\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 27.8,"
                + "\"KgMilkLast12Months\": 9993,"
                + "\"KgECMLast12Months\": 10660,"
                + "\"LastCalvingDate\": \"2013-06-30T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"169\","
                + "\"ExpectedCalvingDate\": \"2014-11-26T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-14T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1421");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow7()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"06524601435\","
                + "\"IllnessDate\": \"2014-04-13T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"06524601435\","
                + "\"IllnessDate\": \"2014-01-22T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"06524601435\","
				+ "\"EventDate\": \"2014-01-30T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"06524601435\","
                + "\"EventDate\": \"2013-12-05T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"06524601435\","
                + "\"AnimalId\": \"06524601435\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 27.9,"
                + "\"KgMilkLast12Months\": 9995,"
                + "\"KgECMLast12Months\": 10430,"
                + "\"LastCalvingDate\": \"2013-07-01T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"170\","
                + "\"ExpectedCalvingDate\": \"2014-11-27T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-15T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1435");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow8()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"06524601444\","
                + "\"IllnessDate\": \"2014-04-14T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"06524601444\","
                + "\"IllnessDate\": \"2014-01-23T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"06524601444\","
				+ "\"EventDate\": \"2014-01-31T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"06524601444\","
                + "\"EventDate\": \"2013-12-06T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"06524601444\","
                + "\"AnimalId\": \"06524601444\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 28.4,"
                + "\"KgMilkLast12Months\": 9913,"
                + "\"KgECMLast12Months\": 10100,"
                + "\"LastCalvingDate\": \"2013-07-02T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"174\","
                + "\"ExpectedCalvingDate\": \"2014-11-28T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-16T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1444");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
	public void createCow9()
	{
		String cow = "{"
				+ "\"odata.metadata\": \"https://dev-dcf-odata.vfltest.dk/DCFOData/CattleWebApi/$metadata#CowIndexCardMobiles\","
				+ "\"value\": ["
				+ "{"
				+ "\"AnimalStatus\": {"
                + "\"Id\": \"129\","
                + "\"AnimalTypeId\": 12,"
                + "\"AnimalStatusCode\": 9,"
                + "\"AnimalStatusText\": \"Ko\","
                + "\"LastUpdatedBy\": null,"
                + "\"LastUpdatedTime\": null"
                + "},"
                + "\"CowIndexCardMobileHealths\": ["
                + "{"
                + "\"Id\": \"59333758\","
                + "\"CowIndexCardMobileId\": \"06524601257\","
                + "\"IllnessDate\": \"2014-04-15T00:00:00\","
                + "\"Text\": \"Klovbeskæring\","
                + "\"Code\": 80"
				+ "},"
				+ "{"
                + "\"Id\": \"58230818\","
                + "\"CowIndexCardMobileId\": \"06524601257\","
                + "\"IllnessDate\": \"2014-01-24T00:00:00\","
                + "\"Text\": \"Yverbetændelse\","
                + "\"Code\": 11"
				+ "}"
				+ "],"
				+ "\"CowIndexCardMobileReproductions\": ["
				+ "{"
				+ "\"Id\": \"189200870\","
				+ "\"CowIndexCardMobileId\": \"06524601257\","
				+ "\"EventDate\": \"2014-02-01T00:00:00\","
				+ "\"Text\": \"Negativ drægt.\","
				+ "\"Code\": 13"
				+ "},"
                + "{"
                + "\"Id\": \"211587845\","
                + "\"CowIndexCardMobileId\": \"06524601257\","
                + "\"EventDate\": \"2013-12-08T00:00:00\"," 
                + "\"Text\": \"Løbning start\","
                + "\"Code\": 21" 
				+ "}"
                + "],"
                + "\"Herd\": {"
                + "\"Id\": \"4651312\","
                + "\"HerdNumber\": 46513,"
                + "\"CHRNumber\": 46513," 
                + "\"AnimalTypeId\": 12,"
                + "\"EndDate\": null,"
                + "\"LastUpdatedBy\": \"RYKLTR\","
                + "\"LastUpdatedTime\": \"2012-08-01T07:22:29\""
        		+ "},"
        		+ "\"Id\": \"06524601257\","
                + "\"AnimalId\": \"06524601257\","
                + "\"HerdId\": \"4651312\","
                + "\"AnimalStatusId\": \"129\","
                + "\"AnimalNumber\": \"5030801946\","
                + "\"PregnancyStatus\": false,"
                + "\"KgECMLastTestDay\": 27.0,"
                + "\"KgMilkLast12Months\": 9923,"
                + "\"KgECMLast12Months\": 10140,"
                + "\"LastCalvingDate\": \"2013-07-02T00:00:00\","
                + "\"LastCalvingNumber\": 5,"
                + "\"SCCLastTestDay\": \"144\","
                + "\"ExpectedCalvingDate\": \"2014-11-29T00:00:00\","
                + "\"LactationValue\": null,"
                + "\"ParaTBLatestAntibody\": 0.1," 
                + "\"ParaTBLatestGroup\": 0,"
                + "\"DateOfBirth\": \"2007-05-17T00:00:00\","
                + "\"CullingCode\": 60,"
                + "\"CullingText\": \"ønskes udsat\","
                + "\"NordicTotalMerit\": 10"
                + "}"
                + "]"
                + "}";
		
		ContentValues values = new ContentValues();
		values.put(FIELD_ID, "1257");
		values.put(FIELD_JSON, cow);
		db.insert(TABLE_COW, null, values);
	}
	
}
